import 'package:flutter_tools/src/base/common.dart';
import 'package:flutter_tools/src/base/file_system.dart';
import 'package:flutter_tools/src/cache.dart';
import 'package:flutter_tools/src/globals.dart' as globals;
import 'package:meta/meta.dart';

import '../p0g_cache.dart';
import '../webui/plugin.dart';

/// flutter-aera's `aera_window` (dart/aera_window), pinned: the binding that
/// puts the padding AERA reports into MediaQuery. AERA builds add it the way
/// WebUI builds add their plugin (package config overlay plus a generated
/// entrypoint), so neither apps nor bricks depend on it.
const kAeraWindowRepo = 'https://github.com/p0g-stack/flutter-aera';
const kAeraWindowCommit = '1ad858287a6bd5cc010cc57539ac0df3b397e9f6';
const kAeraWindowPackage = 'aera_window';

Directory aeraWindowDir() => p0gCacheDir().childDirectory('aera-window');
Directory aeraWindowSource() =>
    aeraWindowDir().childDirectory('src').childDirectory('dart').childDirectory(kAeraWindowPackage);

/// Fetches flutter-aera at the pin (aera_window only) and resolves the
/// package. Stamped by commit; [force] fetches again.
Future<void> precacheAeraWindow({bool force = false}) async {
  final stamp = aeraWindowDir().childFile('stamp');
  final src = aeraWindowDir().childDirectory('src');
  if (!force &&
      stamp.existsSync() &&
      stamp.readAsStringSync() == kAeraWindowCommit &&
      aeraWindowSource()
          .childDirectory('.dart_tool')
          .childFile('package_graph.json')
          .existsSync()) {
    return;
  }
  if (src.existsSync()) src.deleteSync(recursive: true);
  src.createSync(recursive: true);
  Future<void> run(List<String> cmd, {String? dir}) async {
    final code = await globals.processUtils.stream(cmd, workingDirectory: dir ?? src.path);
    if (code != 0) throwToolExit('${cmd.take(3).join(' ')} failed (exit $code).');
  }

  globals.printStatus('Fetching aera_window ${kAeraWindowCommit.substring(0, 7)}...');
  await run(['git', 'init', '-q']);
  await run(['git', 'remote', 'add', 'origin', kAeraWindowRepo]);
  await run(['git', 'sparse-checkout', 'set', 'dart/$kAeraWindowPackage']);
  await run([
    'git',
    'fetch',
    '-q',
    '--depth',
    '1',
    '--filter=blob:none',
    'origin',
    kAeraWindowCommit,
  ]);
  await run(['git', 'checkout', '-q', 'FETCH_HEAD']);
  await run([
    globals.fs.path.join(Cache.flutterRoot!, 'bin', 'flutter'),
    'pub',
    'get',
  ], dir: aeraWindowSource().path);
  stamp.writeAsStringSync(kAeraWindowCommit);
}

/// A `main()` that installs `AeraWindowBinding` and then runs the app's
/// [appImport], passing `args` through when the app's `main` takes them.
/// The binding must be the first one created; this `main` runs before the
/// app's, so the app's own `WidgetsFlutterBinding.ensureInitialized()` and
/// `runApp` get it. An app that creates a binding of its own in `main`
/// (a `WidgetsFlutterBinding` subclass) keeps the injected one: it wins only
/// because it runs first, and nothing else reconciles the two.
@visibleForTesting
String aeraEntrypoint(String appImport) =>
    '''
// Generated by flutter_p0g for AERA builds. Do not edit.
// ignore_for_file: type=lint

import 'package:$kAeraWindowPackage/$kAeraWindowPackage.dart' as aera;

import '$appImport' as app;

typedef _UnaryFunction = dynamic Function(List<String> args);
typedef _NullaryFunction = dynamic Function();

dynamic main(List<String> args) {
  aera.AeraWindowBinding.install();
  final Function entry = app.main;
  if (entry is _UnaryFunction) return entry(args);
  return (entry as _NullaryFunction)();
}
''';

/// The app's package config overlaid with [kAeraWindowPackage] while [body]
/// runs, then restored; [body] gets the generated entrypoint
/// ([aeraEntrypoint]) to build or attach to in place of [target].
Future<T> withAeraWindow<T>(
  Directory project,
  String target,
  Future<T> Function(String entrypoint) body,
) => withEntrypointOverlay(
  project,
  target,
  what: 'AERA',
  sources: [resolvedSource(aeraWindowSource(), 'aera_window', precache: '--aera')],
  entryName: 'aera_main.dart',
  entrypoint: aeraEntrypoint,
  seeds: (_) => const [kAeraWindowPackage],
  body: (overlay) => body(overlay.entrypoint),
);
