import 'dart:convert';

import 'package:flutter_tools/src/base/common.dart';
import 'package:flutter_tools/src/base/file_system.dart';
import 'package:flutter_tools/src/dart/package_map.dart';
import 'package:flutter_tools/src/globals.dart' as globals;
import 'package:meta/meta.dart';
import 'package:package_config/package_config.dart';

import 'flutter_webui.dart';

/// The flutter-webui web plugin. It compiles only against the patched web
/// SDK, so apps depend on `flutter_webui_client` and WebUI builds add the
/// plugin: its packages join the package config for the build, and the
/// build target becomes an entrypoint that registers it before the app's
/// `main()`, the way flutter-tizen registers its embedding plugins from a
/// generated main.
const kWebuiPlugin = 'flutter_webui';

/// [app] (a package_config.json) plus the packages [kWebuiPlugin] needs
/// that [app] lacks, taken from flutter-webui's own resolution ([src] and
/// its package_graph.json [srcGraph]). Packages [app] already has stay as
/// they are. Relative root URIs from [src] are made absolute against
/// [srcConfigDir], the directory holding its package_config.json.
@visibleForTesting
({Map<String, Object?> config, List<String> added}) overlayPackageConfig(
  Map<String, Object?> app,
  Map<String, Object?> src,
  Map<String, Object?> srcGraph, {
  required Uri srcConfigDir,
}) {
  final appPackages = [...(app['packages']! as List).cast<Map<String, Object?>>()];
  final have = {for (final p in appPackages) p['name']! as String};
  final srcPackages = {
    for (final p in (src['packages']! as List).cast<Map<String, Object?>>())
      p['name']! as String: p,
  };
  final deps = {
    for (final p in (srcGraph['packages']! as List).cast<Map<String, Object?>>())
      p['name']! as String: (p['dependencies'] as List? ?? const []).cast<String>(),
  };

  final needed = <String>[];
  final queue = [kWebuiPlugin];
  while (queue.isNotEmpty) {
    final name = queue.removeLast();
    if (needed.contains(name)) continue;
    needed.add(name);
    queue.addAll(deps[name] ?? const []);
  }

  final added = <String>[];
  for (final name in needed) {
    if (have.contains(name)) continue;
    final p = srcPackages[name];
    if (p == null) throwToolExit('flutter-webui resolution lacks package:$name.');
    appPackages.add({...p, 'rootUri': srcConfigDir.resolve(p['rootUri']! as String).toString()});
    added.add(name);
  }
  return (config: {...app, 'packages': appPackages}, added: added..sort());
}

/// A `main()` that registers [kWebuiPlugin] and runs the app's [appImport].
/// flutter_tools wraps it as it wraps any target, so the app's other web
/// plugins register first.
@visibleForTesting
String webuiEntrypoint(String appImport) =>
    '''
// Generated by flutter_p0g build webui. Do not edit.
// ignore_for_file: type=lint

import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:$kWebuiPlugin/flutter_webui_web.dart';

import '$appImport' as app;

typedef _UnaryFunction = dynamic Function(List<String> args);
typedef _NullaryFunction = dynamic Function();

dynamic main() {
  FlutterWebUi.registerWith(webPluginRegistrar);
  final Function entry = app.main;
  if (entry is _UnaryFunction) return entry(<String>[]);
  return (entry as _NullaryFunction)();
}
''';

/// The package config the build uses, overlaid with [kWebuiPlugin] while
/// [body] runs and restored afterwards. [body] gets the entrypoint to build
/// in place of [target].
Future<T> withWebuiPlugin<T>(
  Directory project,
  String target,
  Future<T> Function(String entrypoint) body,
) async {
  final appConfigFile = findPackageConfigFile(project);
  if (appConfigFile == null) throwToolExit('No package config. Run `flutter pub get`.');
  final srcDart = flutterWebuiSource().childDirectory('.dart_tool');
  final srcConfigFile = srcDart.childFile('package_config.json');
  final srcGraphFile = srcDart.childFile('package_graph.json');
  if (!srcConfigFile.existsSync() || !srcGraphFile.existsSync()) {
    throwToolExit('flutter-webui is not resolved. Run `flutter_p0g precache --webui`.');
  }

  final original = appConfigFile.readAsBytesSync();
  final overlay = overlayPackageConfig(
    _json(original),
    _json(srcConfigFile.readAsBytesSync()),
    _json(srcGraphFile.readAsBytesSync()),
    srcConfigDir: srcConfigFile.parent.uri,
  );

  final appConfig = PackageConfig.parseBytes(original, appConfigFile.uri);
  final targetUri = globals.fs.file(target).absolute.uri;
  final appImport = (appConfig.toPackageUri(targetUri) ?? targetUri).toString();
  final entry =
      project
          .childDirectory('.dart_tool')
          .childDirectory('flutter_p0g')
          .childFile('webui_main.dart')
        ..createSync(recursive: true)
        ..writeAsStringSync(webuiEntrypoint(appImport));

  globals.printTrace('WebUI plugin packages added: ${overlay.added.join(', ')}');
  appConfigFile.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(overlay.config));
  try {
    return await body(entry.path);
  } finally {
    appConfigFile.writeAsBytesSync(original);
  }
}

Map<String, Object?> _json(List<int> bytes) =>
    jsonDecode(utf8.decode(bytes)) as Map<String, Object?>;
